/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.api;

import uk.gov.tfl.api.client.client.ApiException;
import uk.gov.tfl.api.client.client.model.AccidentDetail;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for AccidentStatsApi
 */
@Ignore
public class AccidentStatsApiTest {

    private final AccidentStatsApi api = new AccidentStatsApi();

    
    /**
     * Gets all accident details for accidents occuring in the specified year
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accidentStatsGetTest() throws ApiException {
        Integer year = null;
        List<AccidentDetail> response = api.accidentStatsGet(year);

        // TODO: test validations
    }
    
}
