/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.api;

import uk.gov.tfl.api.client.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for AirQualityApi
 */
@Ignore
public class AirQualityApiTest {

    private final AirQualityApi api = new AirQualityApi();

    
    /**
     * Gets air quality data feed
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void airQualityGetTest() throws ApiException {
        Object response = api.airQualityGet();

        // TODO: test validations
    }
    
}
