/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.api;

import uk.gov.tfl.api.client.client.ApiException;
import uk.gov.tfl.api.client.client.model.ActiveServiceType;
import uk.gov.tfl.api.client.client.model.Prediction;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ModeApi
 */
@Ignore
public class ModeApiTest {

    private final ModeApi api = new ModeApi();

    
    /**
     * Gets the next arrival predictions for all stops of a given mode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modeArrivalsTest() throws ApiException {
        String mode = null;
        Integer count = null;
        List<Prediction> response = api.modeArrivals(mode, count);

        // TODO: test validations
    }
    
    /**
     * Returns the service type active for a mode.              Currently only supports tube
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modeGetActiveServiceTypesTest() throws ApiException {
        List<ActiveServiceType> response = api.modeGetActiveServiceTypes();

        // TODO: test validations
    }
    
}
