/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.api;

import uk.gov.tfl.api.client.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for TravelTimeApi
 */
@Ignore
public class TravelTimeApiTest {

    private final TravelTimeApi api = new TravelTimeApi();

    
    /**
     * Gets the TravelTime overlay.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void travelTimeGetCompareOverlayTest() throws ApiException {
        Integer z = null;
        Double pinLat = null;
        Double pinLon = null;
        Double mapCenterLat = null;
        Double mapCenterLon = null;
        String scenarioTitle = null;
        String timeOfDayId = null;
        String modeId = null;
        Integer width = null;
        Integer height = null;
        String direction = null;
        Integer travelTimeInterval = null;
        String compareType = null;
        String compareValue = null;
        Object response = api.travelTimeGetCompareOverlay(z, pinLat, pinLon, mapCenterLat, mapCenterLon, scenarioTitle, timeOfDayId, modeId, width, height, direction, travelTimeInterval, compareType, compareValue);

        // TODO: test validations
    }
    
    /**
     * Gets the TravelTime overlay.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void travelTimeGetOverlayTest() throws ApiException {
        Integer z = null;
        Double pinLat = null;
        Double pinLon = null;
        Double mapCenterLat = null;
        Double mapCenterLon = null;
        String scenarioTitle = null;
        String timeOfDayId = null;
        String modeId = null;
        Integer width = null;
        Integer height = null;
        String direction = null;
        Integer travelTimeInterval = null;
        Object response = api.travelTimeGetOverlay(z, pinLat, pinLon, mapCenterLat, mapCenterLon, scenarioTitle, timeOfDayId, modeId, width, height, direction, travelTimeInterval);

        // TODO: test validations
    }
    
}
