/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * ApiVersionInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class ApiVersionInfo {
  @SerializedName("label")
  private String label = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("assemblies")
  private List<String> assemblies = null;

  public ApiVersionInfo label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ApiVersionInfo timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public ApiVersionInfo version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ApiVersionInfo assemblies(List<String> assemblies) {
    this.assemblies = assemblies;
    return this;
  }

  public ApiVersionInfo addAssembliesItem(String assembliesItem) {
    if (this.assemblies == null) {
      this.assemblies = new ArrayList<String>();
    }
    this.assemblies.add(assembliesItem);
    return this;
  }

   /**
   * Get assemblies
   * @return assemblies
  **/
  @ApiModelProperty(value = "")
  public List<String> getAssemblies() {
    return assemblies;
  }

  public void setAssemblies(List<String> assemblies) {
    this.assemblies = assemblies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiVersionInfo apiVersionInfo = (ApiVersionInfo) o;
    return Objects.equals(this.label, apiVersionInfo.label) &&
        Objects.equals(this.timestamp, apiVersionInfo.timestamp) &&
        Objects.equals(this.version, apiVersionInfo.version) &&
        Objects.equals(this.assemblies, apiVersionInfo.assemblies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, timestamp, version, assemblies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiVersionInfo {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    assemblies: ").append(toIndentedString(assemblies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

