/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Crowding
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class Crowding {
  @SerializedName("passengerFlows")
  private List<PassengerFlow> passengerFlows = null;

  @SerializedName("trainLoadings")
  private List<TrainLoading> trainLoadings = null;

  public Crowding passengerFlows(List<PassengerFlow> passengerFlows) {
    this.passengerFlows = passengerFlows;
    return this;
  }

  public Crowding addPassengerFlowsItem(PassengerFlow passengerFlowsItem) {
    if (this.passengerFlows == null) {
      this.passengerFlows = new ArrayList<PassengerFlow>();
    }
    this.passengerFlows.add(passengerFlowsItem);
    return this;
  }

   /**
   * Busiest times at a station (static information)
   * @return passengerFlows
  **/
  @ApiModelProperty(value = "Busiest times at a station (static information)")
  public List<PassengerFlow> getPassengerFlows() {
    return passengerFlows;
  }

  public void setPassengerFlows(List<PassengerFlow> passengerFlows) {
    this.passengerFlows = passengerFlows;
  }

  public Crowding trainLoadings(List<TrainLoading> trainLoadings) {
    this.trainLoadings = trainLoadings;
    return this;
  }

  public Crowding addTrainLoadingsItem(TrainLoading trainLoadingsItem) {
    if (this.trainLoadings == null) {
      this.trainLoadings = new ArrayList<TrainLoading>();
    }
    this.trainLoadings.add(trainLoadingsItem);
    return this;
  }

   /**
   * Train Loading on a scale 1-6, 1 being \&quot;Very quiet\&quot; and 6 being \&quot;Exceptionally busy\&quot; (static information)
   * @return trainLoadings
  **/
  @ApiModelProperty(value = "Train Loading on a scale 1-6, 1 being \"Very quiet\" and 6 being \"Exceptionally busy\" (static information)")
  public List<TrainLoading> getTrainLoadings() {
    return trainLoadings;
  }

  public void setTrainLoadings(List<TrainLoading> trainLoadings) {
    this.trainLoadings = trainLoadings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Crowding crowding = (Crowding) o;
    return Objects.equals(this.passengerFlows, crowding.passengerFlows) &&
        Objects.equals(this.trainLoadings, crowding.trainLoadings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerFlows, trainLoadings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Crowding {\n");
    
    sb.append("    passengerFlows: ").append(toIndentedString(passengerFlows)).append("\n");
    sb.append("    trainLoadings: ").append(toIndentedString(trainLoadings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

