/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents a disruption to a route within the transport network.
 */
@ApiModel(description = "Represents a disruption to a route within the transport network.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class Disruption {
  /**
   * Gets or sets the category of this dispruption.
   */
  @JsonAdapter(CategoryEnum.Adapter.class)
  public enum CategoryEnum {
    UNDEFINED("Undefined"),
    
    REALTIME("RealTime"),
    
    PLANNEDWORK("PlannedWork"),
    
    INFORMATION("Information"),
    
    EVENT("Event"),
    
    CROWDING("Crowding"),
    
    STATUSALERT("StatusAlert");

    private String value;

    CategoryEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CategoryEnum fromValue(String text) {
      for (CategoryEnum b : CategoryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CategoryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CategoryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CategoryEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CategoryEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("category")
  private CategoryEnum category = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("categoryDescription")
  private String categoryDescription = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("summary")
  private String summary = null;

  @SerializedName("additionalInfo")
  private String additionalInfo = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("lastUpdate")
  private OffsetDateTime lastUpdate = null;

  @SerializedName("affectedRoutes")
  private List<RouteSection> affectedRoutes = null;

  @SerializedName("affectedStops")
  private List<StopPoint> affectedStops = null;

  @SerializedName("closureText")
  private String closureText = null;

  public Disruption category(CategoryEnum category) {
    this.category = category;
    return this;
  }

   /**
   * Gets or sets the category of this dispruption.
   * @return category
  **/
  @ApiModelProperty(value = "Gets or sets the category of this dispruption.")
  public CategoryEnum getCategory() {
    return category;
  }

  public void setCategory(CategoryEnum category) {
    this.category = category;
  }

  public Disruption type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Gets or sets the disruption type of this dispruption.
   * @return type
  **/
  @ApiModelProperty(value = "Gets or sets the disruption type of this dispruption.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Disruption categoryDescription(String categoryDescription) {
    this.categoryDescription = categoryDescription;
    return this;
  }

   /**
   * Gets or sets the description of the category.
   * @return categoryDescription
  **/
  @ApiModelProperty(value = "Gets or sets the description of the category.")
  public String getCategoryDescription() {
    return categoryDescription;
  }

  public void setCategoryDescription(String categoryDescription) {
    this.categoryDescription = categoryDescription;
  }

  public Disruption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Gets or sets the description of this disruption.
   * @return description
  **/
  @ApiModelProperty(value = "Gets or sets the description of this disruption.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Disruption summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Gets or sets the summary of this disruption.
   * @return summary
  **/
  @ApiModelProperty(value = "Gets or sets the summary of this disruption.")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public Disruption additionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Gets or sets the additionaInfo of this disruption.
   * @return additionalInfo
  **/
  @ApiModelProperty(value = "Gets or sets the additionaInfo of this disruption.")
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public Disruption created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Gets or sets the date/time when this disruption was created.
   * @return created
  **/
  @ApiModelProperty(value = "Gets or sets the date/time when this disruption was created.")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public Disruption lastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Gets or sets the date/time when this disruption was last updated.
   * @return lastUpdate
  **/
  @ApiModelProperty(value = "Gets or sets the date/time when this disruption was last updated.")
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public Disruption affectedRoutes(List<RouteSection> affectedRoutes) {
    this.affectedRoutes = affectedRoutes;
    return this;
  }

  public Disruption addAffectedRoutesItem(RouteSection affectedRoutesItem) {
    if (this.affectedRoutes == null) {
      this.affectedRoutes = new ArrayList<RouteSection>();
    }
    this.affectedRoutes.add(affectedRoutesItem);
    return this;
  }

   /**
   * Gets or sets the routes affected by this disruption
   * @return affectedRoutes
  **/
  @ApiModelProperty(value = "Gets or sets the routes affected by this disruption")
  public List<RouteSection> getAffectedRoutes() {
    return affectedRoutes;
  }

  public void setAffectedRoutes(List<RouteSection> affectedRoutes) {
    this.affectedRoutes = affectedRoutes;
  }

  public Disruption affectedStops(List<StopPoint> affectedStops) {
    this.affectedStops = affectedStops;
    return this;
  }

  public Disruption addAffectedStopsItem(StopPoint affectedStopsItem) {
    if (this.affectedStops == null) {
      this.affectedStops = new ArrayList<StopPoint>();
    }
    this.affectedStops.add(affectedStopsItem);
    return this;
  }

   /**
   * Gets or sets the stops affected by this disruption
   * @return affectedStops
  **/
  @ApiModelProperty(value = "Gets or sets the stops affected by this disruption")
  public List<StopPoint> getAffectedStops() {
    return affectedStops;
  }

  public void setAffectedStops(List<StopPoint> affectedStops) {
    this.affectedStops = affectedStops;
  }

  public Disruption closureText(String closureText) {
    this.closureText = closureText;
    return this;
  }

   /**
   * Text describing the closure type
   * @return closureText
  **/
  @ApiModelProperty(value = "Text describing the closure type")
  public String getClosureText() {
    return closureText;
  }

  public void setClosureText(String closureText) {
    this.closureText = closureText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Disruption disruption = (Disruption) o;
    return Objects.equals(this.category, disruption.category) &&
        Objects.equals(this.type, disruption.type) &&
        Objects.equals(this.categoryDescription, disruption.categoryDescription) &&
        Objects.equals(this.description, disruption.description) &&
        Objects.equals(this.summary, disruption.summary) &&
        Objects.equals(this.additionalInfo, disruption.additionalInfo) &&
        Objects.equals(this.created, disruption.created) &&
        Objects.equals(this.lastUpdate, disruption.lastUpdate) &&
        Objects.equals(this.affectedRoutes, disruption.affectedRoutes) &&
        Objects.equals(this.affectedStops, disruption.affectedStops) &&
        Objects.equals(this.closureText, disruption.closureText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, type, categoryDescription, description, summary, additionalInfo, created, lastUpdate, affectedRoutes, affectedStops, closureText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Disruption {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    categoryDescription: ").append(toIndentedString(categoryDescription)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    affectedRoutes: ").append(toIndentedString(affectedRoutes)).append("\n");
    sb.append("    affectedStops: ").append(toIndentedString(affectedStops)).append("\n");
    sb.append("    closureText: ").append(toIndentedString(closureText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

