/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * DisruptedPoint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class DisruptedPoint {
  @SerializedName("atcoCode")
  private String atcoCode = null;

  @SerializedName("fromDate")
  private OffsetDateTime fromDate = null;

  @SerializedName("toDate")
  private OffsetDateTime toDate = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("commonName")
  private String commonName = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("mode")
  private String mode = null;

  @SerializedName("stationAtcoCode")
  private String stationAtcoCode = null;

  @SerializedName("appearance")
  private String appearance = null;

  @SerializedName("additionalInformation")
  private String additionalInformation = null;

  public DisruptedPoint atcoCode(String atcoCode) {
    this.atcoCode = atcoCode;
    return this;
  }

   /**
   * Get atcoCode
   * @return atcoCode
  **/
  @ApiModelProperty(value = "")
  public String getAtcoCode() {
    return atcoCode;
  }

  public void setAtcoCode(String atcoCode) {
    this.atcoCode = atcoCode;
  }

  public DisruptedPoint fromDate(OffsetDateTime fromDate) {
    this.fromDate = fromDate;
    return this;
  }

   /**
   * Get fromDate
   * @return fromDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getFromDate() {
    return fromDate;
  }

  public void setFromDate(OffsetDateTime fromDate) {
    this.fromDate = fromDate;
  }

  public DisruptedPoint toDate(OffsetDateTime toDate) {
    this.toDate = toDate;
    return this;
  }

   /**
   * Get toDate
   * @return toDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getToDate() {
    return toDate;
  }

  public void setToDate(OffsetDateTime toDate) {
    this.toDate = toDate;
  }

  public DisruptedPoint description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DisruptedPoint commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * Get commonName
   * @return commonName
  **/
  @ApiModelProperty(value = "")
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public DisruptedPoint type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DisruptedPoint mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(value = "")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public DisruptedPoint stationAtcoCode(String stationAtcoCode) {
    this.stationAtcoCode = stationAtcoCode;
    return this;
  }

   /**
   * Get stationAtcoCode
   * @return stationAtcoCode
  **/
  @ApiModelProperty(value = "")
  public String getStationAtcoCode() {
    return stationAtcoCode;
  }

  public void setStationAtcoCode(String stationAtcoCode) {
    this.stationAtcoCode = stationAtcoCode;
  }

  public DisruptedPoint appearance(String appearance) {
    this.appearance = appearance;
    return this;
  }

   /**
   * Get appearance
   * @return appearance
  **/
  @ApiModelProperty(value = "")
  public String getAppearance() {
    return appearance;
  }

  public void setAppearance(String appearance) {
    this.appearance = appearance;
  }

  public DisruptedPoint additionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Get additionalInformation
   * @return additionalInformation
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisruptedPoint disruptedPoint = (DisruptedPoint) o;
    return Objects.equals(this.atcoCode, disruptedPoint.atcoCode) &&
        Objects.equals(this.fromDate, disruptedPoint.fromDate) &&
        Objects.equals(this.toDate, disruptedPoint.toDate) &&
        Objects.equals(this.description, disruptedPoint.description) &&
        Objects.equals(this.commonName, disruptedPoint.commonName) &&
        Objects.equals(this.type, disruptedPoint.type) &&
        Objects.equals(this.mode, disruptedPoint.mode) &&
        Objects.equals(this.stationAtcoCode, disruptedPoint.stationAtcoCode) &&
        Objects.equals(this.appearance, disruptedPoint.appearance) &&
        Objects.equals(this.additionalInformation, disruptedPoint.additionalInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atcoCode, fromDate, toDate, description, commonName, type, mode, stationAtcoCode, appearance, additionalInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisruptedPoint {\n");
    
    sb.append("    atcoCode: ").append(toIndentedString(atcoCode)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    stationAtcoCode: ").append(toIndentedString(stationAtcoCode)).append("\n");
    sb.append("    appearance: ").append(toIndentedString(appearance)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

