/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * FareBounds
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class FareBounds {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("from")
  private String from = null;

  @SerializedName("to")
  private String to = null;

  @SerializedName("via")
  private String via = null;

  @SerializedName("routeCode")
  private String routeCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("operator")
  private String operator = null;

  @SerializedName("displayOrder")
  private Integer displayOrder = null;

  @SerializedName("isPopularFare")
  private Boolean isPopularFare = null;

  @SerializedName("isPopularTravelCard")
  private Boolean isPopularTravelCard = null;

  @SerializedName("isTour")
  private Boolean isTour = null;

  @SerializedName("messages")
  private List<Message> messages = null;

  public FareBounds id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public FareBounds from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(value = "")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public FareBounds to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public FareBounds via(String via) {
    this.via = via;
    return this;
  }

   /**
   * Get via
   * @return via
  **/
  @ApiModelProperty(value = "")
  public String getVia() {
    return via;
  }

  public void setVia(String via) {
    this.via = via;
  }

  public FareBounds routeCode(String routeCode) {
    this.routeCode = routeCode;
    return this;
  }

   /**
   * Get routeCode
   * @return routeCode
  **/
  @ApiModelProperty(value = "")
  public String getRouteCode() {
    return routeCode;
  }

  public void setRouteCode(String routeCode) {
    this.routeCode = routeCode;
  }

  public FareBounds description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public FareBounds displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public FareBounds operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @ApiModelProperty(value = "")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }

  public FareBounds displayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
    return this;
  }

   /**
   * Get displayOrder
   * @return displayOrder
  **/
  @ApiModelProperty(value = "")
  public Integer getDisplayOrder() {
    return displayOrder;
  }

  public void setDisplayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
  }

  public FareBounds isPopularFare(Boolean isPopularFare) {
    this.isPopularFare = isPopularFare;
    return this;
  }

   /**
   * Get isPopularFare
   * @return isPopularFare
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPopularFare() {
    return isPopularFare;
  }

  public void setIsPopularFare(Boolean isPopularFare) {
    this.isPopularFare = isPopularFare;
  }

  public FareBounds isPopularTravelCard(Boolean isPopularTravelCard) {
    this.isPopularTravelCard = isPopularTravelCard;
    return this;
  }

   /**
   * Get isPopularTravelCard
   * @return isPopularTravelCard
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPopularTravelCard() {
    return isPopularTravelCard;
  }

  public void setIsPopularTravelCard(Boolean isPopularTravelCard) {
    this.isPopularTravelCard = isPopularTravelCard;
  }

  public FareBounds isTour(Boolean isTour) {
    this.isTour = isTour;
    return this;
  }

   /**
   * Get isTour
   * @return isTour
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsTour() {
    return isTour;
  }

  public void setIsTour(Boolean isTour) {
    this.isTour = isTour;
  }

  public FareBounds messages(List<Message> messages) {
    this.messages = messages;
    return this;
  }

  public FareBounds addMessagesItem(Message messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<Message>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(value = "")
  public List<Message> getMessages() {
    return messages;
  }

  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FareBounds fareBounds = (FareBounds) o;
    return Objects.equals(this.id, fareBounds.id) &&
        Objects.equals(this.from, fareBounds.from) &&
        Objects.equals(this.to, fareBounds.to) &&
        Objects.equals(this.via, fareBounds.via) &&
        Objects.equals(this.routeCode, fareBounds.routeCode) &&
        Objects.equals(this.description, fareBounds.description) &&
        Objects.equals(this.displayName, fareBounds.displayName) &&
        Objects.equals(this.operator, fareBounds.operator) &&
        Objects.equals(this.displayOrder, fareBounds.displayOrder) &&
        Objects.equals(this.isPopularFare, fareBounds.isPopularFare) &&
        Objects.equals(this.isPopularTravelCard, fareBounds.isPopularTravelCard) &&
        Objects.equals(this.isTour, fareBounds.isTour) &&
        Objects.equals(this.messages, fareBounds.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, from, to, via, routeCode, description, displayName, operator, displayOrder, isPopularFare, isPopularTravelCard, isTour, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FareBounds {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    via: ").append(toIndentedString(via)).append("\n");
    sb.append("    routeCode: ").append(toIndentedString(routeCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    displayOrder: ").append(toIndentedString(displayOrder)).append("\n");
    sb.append("    isPopularFare: ").append(toIndentedString(isPopularFare)).append("\n");
    sb.append("    isPopularTravelCard: ").append(toIndentedString(isPopularTravelCard)).append("\n");
    sb.append("    isTour: ").append(toIndentedString(isTour)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

