/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Line
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class Line {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("modeName")
  private String modeName = null;

  @SerializedName("disruptions")
  private List<Disruption> disruptions = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("modified")
  private OffsetDateTime modified = null;

  @SerializedName("lineStatuses")
  private List<LineStatus> lineStatuses = null;

  @SerializedName("routeSections")
  private List<MatchedRoute> routeSections = null;

  @SerializedName("serviceTypes")
  private List<LineServiceTypeInfo> serviceTypes = null;

  @SerializedName("crowding")
  private Crowding crowding = null;

  public Line id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Line name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Line modeName(String modeName) {
    this.modeName = modeName;
    return this;
  }

   /**
   * Get modeName
   * @return modeName
  **/
  @ApiModelProperty(value = "")
  public String getModeName() {
    return modeName;
  }

  public void setModeName(String modeName) {
    this.modeName = modeName;
  }

  public Line disruptions(List<Disruption> disruptions) {
    this.disruptions = disruptions;
    return this;
  }

  public Line addDisruptionsItem(Disruption disruptionsItem) {
    if (this.disruptions == null) {
      this.disruptions = new ArrayList<Disruption>();
    }
    this.disruptions.add(disruptionsItem);
    return this;
  }

   /**
   * Get disruptions
   * @return disruptions
  **/
  @ApiModelProperty(value = "")
  public List<Disruption> getDisruptions() {
    return disruptions;
  }

  public void setDisruptions(List<Disruption> disruptions) {
    this.disruptions = disruptions;
  }

  public Line created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public Line modified(OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }

  public Line lineStatuses(List<LineStatus> lineStatuses) {
    this.lineStatuses = lineStatuses;
    return this;
  }

  public Line addLineStatusesItem(LineStatus lineStatusesItem) {
    if (this.lineStatuses == null) {
      this.lineStatuses = new ArrayList<LineStatus>();
    }
    this.lineStatuses.add(lineStatusesItem);
    return this;
  }

   /**
   * Get lineStatuses
   * @return lineStatuses
  **/
  @ApiModelProperty(value = "")
  public List<LineStatus> getLineStatuses() {
    return lineStatuses;
  }

  public void setLineStatuses(List<LineStatus> lineStatuses) {
    this.lineStatuses = lineStatuses;
  }

  public Line routeSections(List<MatchedRoute> routeSections) {
    this.routeSections = routeSections;
    return this;
  }

  public Line addRouteSectionsItem(MatchedRoute routeSectionsItem) {
    if (this.routeSections == null) {
      this.routeSections = new ArrayList<MatchedRoute>();
    }
    this.routeSections.add(routeSectionsItem);
    return this;
  }

   /**
   * Get routeSections
   * @return routeSections
  **/
  @ApiModelProperty(value = "")
  public List<MatchedRoute> getRouteSections() {
    return routeSections;
  }

  public void setRouteSections(List<MatchedRoute> routeSections) {
    this.routeSections = routeSections;
  }

  public Line serviceTypes(List<LineServiceTypeInfo> serviceTypes) {
    this.serviceTypes = serviceTypes;
    return this;
  }

  public Line addServiceTypesItem(LineServiceTypeInfo serviceTypesItem) {
    if (this.serviceTypes == null) {
      this.serviceTypes = new ArrayList<LineServiceTypeInfo>();
    }
    this.serviceTypes.add(serviceTypesItem);
    return this;
  }

   /**
   * Get serviceTypes
   * @return serviceTypes
  **/
  @ApiModelProperty(value = "")
  public List<LineServiceTypeInfo> getServiceTypes() {
    return serviceTypes;
  }

  public void setServiceTypes(List<LineServiceTypeInfo> serviceTypes) {
    this.serviceTypes = serviceTypes;
  }

  public Line crowding(Crowding crowding) {
    this.crowding = crowding;
    return this;
  }

   /**
   * Get crowding
   * @return crowding
  **/
  @ApiModelProperty(value = "")
  public Crowding getCrowding() {
    return crowding;
  }

  public void setCrowding(Crowding crowding) {
    this.crowding = crowding;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Line line = (Line) o;
    return Objects.equals(this.id, line.id) &&
        Objects.equals(this.name, line.name) &&
        Objects.equals(this.modeName, line.modeName) &&
        Objects.equals(this.disruptions, line.disruptions) &&
        Objects.equals(this.created, line.created) &&
        Objects.equals(this.modified, line.modified) &&
        Objects.equals(this.lineStatuses, line.lineStatuses) &&
        Objects.equals(this.routeSections, line.routeSections) &&
        Objects.equals(this.serviceTypes, line.serviceTypes) &&
        Objects.equals(this.crowding, line.crowding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, modeName, disruptions, created, modified, lineStatuses, routeSections, serviceTypes, crowding);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Line {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    modeName: ").append(toIndentedString(modeName)).append("\n");
    sb.append("    disruptions: ").append(toIndentedString(disruptions)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    lineStatuses: ").append(toIndentedString(lineStatuses)).append("\n");
    sb.append("    routeSections: ").append(toIndentedString(routeSections)).append("\n");
    sb.append("    serviceTypes: ").append(toIndentedString(serviceTypes)).append("\n");
    sb.append("    crowding: ").append(toIndentedString(crowding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

