/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * LineRouteSection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class LineRouteSection {
  @SerializedName("routeId")
  private Integer routeId = null;

  @SerializedName("direction")
  private String direction = null;

  @SerializedName("destination")
  private String destination = null;

  @SerializedName("fromStation")
  private String fromStation = null;

  @SerializedName("toStation")
  private String toStation = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  @SerializedName("vehicleDestinationText")
  private String vehicleDestinationText = null;

  public LineRouteSection routeId(Integer routeId) {
    this.routeId = routeId;
    return this;
  }

   /**
   * Get routeId
   * @return routeId
  **/
  @ApiModelProperty(value = "")
  public Integer getRouteId() {
    return routeId;
  }

  public void setRouteId(Integer routeId) {
    this.routeId = routeId;
  }

  public LineRouteSection direction(String direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @ApiModelProperty(value = "")
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public LineRouteSection destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  @ApiModelProperty(value = "")
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }

  public LineRouteSection fromStation(String fromStation) {
    this.fromStation = fromStation;
    return this;
  }

   /**
   * Get fromStation
   * @return fromStation
  **/
  @ApiModelProperty(value = "")
  public String getFromStation() {
    return fromStation;
  }

  public void setFromStation(String fromStation) {
    this.fromStation = fromStation;
  }

  public LineRouteSection toStation(String toStation) {
    this.toStation = toStation;
    return this;
  }

   /**
   * Get toStation
   * @return toStation
  **/
  @ApiModelProperty(value = "")
  public String getToStation() {
    return toStation;
  }

  public void setToStation(String toStation) {
    this.toStation = toStation;
  }

  public LineRouteSection serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Get serviceType
   * @return serviceType
  **/
  @ApiModelProperty(value = "")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }

  public LineRouteSection vehicleDestinationText(String vehicleDestinationText) {
    this.vehicleDestinationText = vehicleDestinationText;
    return this;
  }

   /**
   * Get vehicleDestinationText
   * @return vehicleDestinationText
  **/
  @ApiModelProperty(value = "")
  public String getVehicleDestinationText() {
    return vehicleDestinationText;
  }

  public void setVehicleDestinationText(String vehicleDestinationText) {
    this.vehicleDestinationText = vehicleDestinationText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineRouteSection lineRouteSection = (LineRouteSection) o;
    return Objects.equals(this.routeId, lineRouteSection.routeId) &&
        Objects.equals(this.direction, lineRouteSection.direction) &&
        Objects.equals(this.destination, lineRouteSection.destination) &&
        Objects.equals(this.fromStation, lineRouteSection.fromStation) &&
        Objects.equals(this.toStation, lineRouteSection.toStation) &&
        Objects.equals(this.serviceType, lineRouteSection.serviceType) &&
        Objects.equals(this.vehicleDestinationText, lineRouteSection.vehicleDestinationText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeId, direction, destination, fromStation, toStation, serviceType, vehicleDestinationText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineRouteSection {\n");
    
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    fromStation: ").append(toIndentedString(fromStation)).append("\n");
    sb.append("    toStation: ").append(toIndentedString(toStation)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    vehicleDestinationText: ").append(toIndentedString(vehicleDestinationText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

