/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * Description of a Route used in Route search results.
 */
@ApiModel(description = "Description of a Route used in Route search results.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class MatchedRoute {
  @SerializedName("routeCode")
  private String routeCode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("direction")
  private String direction = null;

  @SerializedName("originationName")
  private String originationName = null;

  @SerializedName("destinationName")
  private String destinationName = null;

  @SerializedName("originator")
  private String originator = null;

  @SerializedName("destination")
  private String destination = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  @SerializedName("validTo")
  private OffsetDateTime validTo = null;

  @SerializedName("validFrom")
  private OffsetDateTime validFrom = null;

  public MatchedRoute routeCode(String routeCode) {
    this.routeCode = routeCode;
    return this;
  }

   /**
   * The route code
   * @return routeCode
  **/
  @ApiModelProperty(value = "The route code")
  public String getRouteCode() {
    return routeCode;
  }

  public void setRouteCode(String routeCode) {
    this.routeCode = routeCode;
  }

  public MatchedRoute name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name such as \&quot;72\&quot;
   * @return name
  **/
  @ApiModelProperty(value = "Name such as \"72\"")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MatchedRoute direction(String direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Inbound or Outbound
   * @return direction
  **/
  @ApiModelProperty(value = "Inbound or Outbound")
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public MatchedRoute originationName(String originationName) {
    this.originationName = originationName;
    return this;
  }

   /**
   * The name of the Origin StopPoint
   * @return originationName
  **/
  @ApiModelProperty(value = "The name of the Origin StopPoint")
  public String getOriginationName() {
    return originationName;
  }

  public void setOriginationName(String originationName) {
    this.originationName = originationName;
  }

  public MatchedRoute destinationName(String destinationName) {
    this.destinationName = destinationName;
    return this;
  }

   /**
   * The name of the Destination StopPoint
   * @return destinationName
  **/
  @ApiModelProperty(value = "The name of the Destination StopPoint")
  public String getDestinationName() {
    return destinationName;
  }

  public void setDestinationName(String destinationName) {
    this.destinationName = destinationName;
  }

  public MatchedRoute originator(String originator) {
    this.originator = originator;
    return this;
  }

   /**
   * The Id (NaPTAN code) of the Origin StopPoint
   * @return originator
  **/
  @ApiModelProperty(value = "The Id (NaPTAN code) of the Origin StopPoint")
  public String getOriginator() {
    return originator;
  }

  public void setOriginator(String originator) {
    this.originator = originator;
  }

  public MatchedRoute destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * The Id (NaPTAN code) or the Destination StopPoint
   * @return destination
  **/
  @ApiModelProperty(value = "The Id (NaPTAN code) or the Destination StopPoint")
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }

  public MatchedRoute serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Regular or Night
   * @return serviceType
  **/
  @ApiModelProperty(value = "Regular or Night")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }

  public MatchedRoute validTo(OffsetDateTime validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * The DateTime that the Service containing this Route is valid until.
   * @return validTo
  **/
  @ApiModelProperty(value = "The DateTime that the Service containing this Route is valid until.")
  public OffsetDateTime getValidTo() {
    return validTo;
  }

  public void setValidTo(OffsetDateTime validTo) {
    this.validTo = validTo;
  }

  public MatchedRoute validFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * The DateTime that the Service containing this Route is valid from.
   * @return validFrom
  **/
  @ApiModelProperty(value = "The DateTime that the Service containing this Route is valid from.")
  public OffsetDateTime getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchedRoute matchedRoute = (MatchedRoute) o;
    return Objects.equals(this.routeCode, matchedRoute.routeCode) &&
        Objects.equals(this.name, matchedRoute.name) &&
        Objects.equals(this.direction, matchedRoute.direction) &&
        Objects.equals(this.originationName, matchedRoute.originationName) &&
        Objects.equals(this.destinationName, matchedRoute.destinationName) &&
        Objects.equals(this.originator, matchedRoute.originator) &&
        Objects.equals(this.destination, matchedRoute.destination) &&
        Objects.equals(this.serviceType, matchedRoute.serviceType) &&
        Objects.equals(this.validTo, matchedRoute.validTo) &&
        Objects.equals(this.validFrom, matchedRoute.validFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeCode, name, direction, originationName, destinationName, originator, destination, serviceType, validTo, validFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchedRoute {\n");
    
    sb.append("    routeCode: ").append(toIndentedString(routeCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    originationName: ").append(toIndentedString(originationName)).append("\n");
    sb.append("    destinationName: ").append(toIndentedString(destinationName)).append("\n");
    sb.append("    originator: ").append(toIndentedString(originator)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

