/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Mode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class Mode {
  @SerializedName("isTflService")
  private Boolean isTflService = null;

  @SerializedName("isFarePaying")
  private Boolean isFarePaying = null;

  @SerializedName("isScheduledService")
  private Boolean isScheduledService = null;

  @SerializedName("modeName")
  private String modeName = null;

  public Mode isTflService(Boolean isTflService) {
    this.isTflService = isTflService;
    return this;
  }

   /**
   * Get isTflService
   * @return isTflService
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsTflService() {
    return isTflService;
  }

  public void setIsTflService(Boolean isTflService) {
    this.isTflService = isTflService;
  }

  public Mode isFarePaying(Boolean isFarePaying) {
    this.isFarePaying = isFarePaying;
    return this;
  }

   /**
   * Get isFarePaying
   * @return isFarePaying
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsFarePaying() {
    return isFarePaying;
  }

  public void setIsFarePaying(Boolean isFarePaying) {
    this.isFarePaying = isFarePaying;
  }

  public Mode isScheduledService(Boolean isScheduledService) {
    this.isScheduledService = isScheduledService;
    return this;
  }

   /**
   * Get isScheduledService
   * @return isScheduledService
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsScheduledService() {
    return isScheduledService;
  }

  public void setIsScheduledService(Boolean isScheduledService) {
    this.isScheduledService = isScheduledService;
  }

  public Mode modeName(String modeName) {
    this.modeName = modeName;
    return this;
  }

   /**
   * Get modeName
   * @return modeName
  **/
  @ApiModelProperty(value = "")
  public String getModeName() {
    return modeName;
  }

  public void setModeName(String modeName) {
    this.modeName = modeName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mode mode = (Mode) o;
    return Objects.equals(this.isTflService, mode.isTflService) &&
        Objects.equals(this.isFarePaying, mode.isFarePaying) &&
        Objects.equals(this.isScheduledService, mode.isScheduledService) &&
        Objects.equals(this.modeName, mode.modeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isTflService, isFarePaying, isScheduledService, modeName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mode {\n");
    
    sb.append("    isTflService: ").append(toIndentedString(isTflService)).append("\n");
    sb.append("    isFarePaying: ").append(toIndentedString(isFarePaying)).append("\n");
    sb.append("    isScheduledService: ").append(toIndentedString(isScheduledService)).append("\n");
    sb.append("    modeName: ").append(toIndentedString(modeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

