/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * OrderedRoute
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class OrderedRoute {
  @SerializedName("name")
  private String name = null;

  @SerializedName("naptanIds")
  private List<String> naptanIds = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  public OrderedRoute name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrderedRoute naptanIds(List<String> naptanIds) {
    this.naptanIds = naptanIds;
    return this;
  }

  public OrderedRoute addNaptanIdsItem(String naptanIdsItem) {
    if (this.naptanIds == null) {
      this.naptanIds = new ArrayList<String>();
    }
    this.naptanIds.add(naptanIdsItem);
    return this;
  }

   /**
   * Get naptanIds
   * @return naptanIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getNaptanIds() {
    return naptanIds;
  }

  public void setNaptanIds(List<String> naptanIds) {
    this.naptanIds = naptanIds;
  }

  public OrderedRoute serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Get serviceType
   * @return serviceType
  **/
  @ApiModelProperty(value = "")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderedRoute orderedRoute = (OrderedRoute) o;
    return Objects.equals(this.name, orderedRoute.name) &&
        Objects.equals(this.naptanIds, orderedRoute.naptanIds) &&
        Objects.equals(this.serviceType, orderedRoute.serviceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, naptanIds, serviceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderedRoute {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    naptanIds: ").append(toIndentedString(naptanIds)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

