/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * RoadDisruptionLine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class RoadDisruptionLine {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("roadDisruptionId")
  private String roadDisruptionId = null;

  @SerializedName("isDiversion")
  private Boolean isDiversion = null;

  @SerializedName("multiLineString")
  private DbGeography multiLineString = null;

  @SerializedName("startDate")
  private OffsetDateTime startDate = null;

  @SerializedName("endDate")
  private OffsetDateTime endDate = null;

  @SerializedName("startTime")
  private String startTime = null;

  @SerializedName("endTime")
  private String endTime = null;

  public RoadDisruptionLine id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RoadDisruptionLine roadDisruptionId(String roadDisruptionId) {
    this.roadDisruptionId = roadDisruptionId;
    return this;
  }

   /**
   * Get roadDisruptionId
   * @return roadDisruptionId
  **/
  @ApiModelProperty(value = "")
  public String getRoadDisruptionId() {
    return roadDisruptionId;
  }

  public void setRoadDisruptionId(String roadDisruptionId) {
    this.roadDisruptionId = roadDisruptionId;
  }

  public RoadDisruptionLine isDiversion(Boolean isDiversion) {
    this.isDiversion = isDiversion;
    return this;
  }

   /**
   * Get isDiversion
   * @return isDiversion
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDiversion() {
    return isDiversion;
  }

  public void setIsDiversion(Boolean isDiversion) {
    this.isDiversion = isDiversion;
  }

  public RoadDisruptionLine multiLineString(DbGeography multiLineString) {
    this.multiLineString = multiLineString;
    return this;
  }

   /**
   * Get multiLineString
   * @return multiLineString
  **/
  @ApiModelProperty(value = "")
  public DbGeography getMultiLineString() {
    return multiLineString;
  }

  public void setMultiLineString(DbGeography multiLineString) {
    this.multiLineString = multiLineString;
  }

  public RoadDisruptionLine startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public RoadDisruptionLine endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public RoadDisruptionLine startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(value = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public RoadDisruptionLine endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(value = "")
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoadDisruptionLine roadDisruptionLine = (RoadDisruptionLine) o;
    return Objects.equals(this.id, roadDisruptionLine.id) &&
        Objects.equals(this.roadDisruptionId, roadDisruptionLine.roadDisruptionId) &&
        Objects.equals(this.isDiversion, roadDisruptionLine.isDiversion) &&
        Objects.equals(this.multiLineString, roadDisruptionLine.multiLineString) &&
        Objects.equals(this.startDate, roadDisruptionLine.startDate) &&
        Objects.equals(this.endDate, roadDisruptionLine.endDate) &&
        Objects.equals(this.startTime, roadDisruptionLine.startTime) &&
        Objects.equals(this.endTime, roadDisruptionLine.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, roadDisruptionId, isDiversion, multiLineString, startDate, endDate, startTime, endTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoadDisruptionLine {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    roadDisruptionId: ").append(toIndentedString(roadDisruptionId)).append("\n");
    sb.append("    isDiversion: ").append(toIndentedString(isDiversion)).append("\n");
    sb.append("    multiLineString: ").append(toIndentedString(multiLineString)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

