/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * RouteOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class RouteOption {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("directions")
  private List<String> directions = null;

  @SerializedName("lineIdentifier")
  private Identifier lineIdentifier = null;

  public RouteOption id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The Id of the route
   * @return id
  **/
  @ApiModelProperty(value = "The Id of the route")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RouteOption name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name such as \&quot;72\&quot;
   * @return name
  **/
  @ApiModelProperty(value = "Name such as \"72\"")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RouteOption directions(List<String> directions) {
    this.directions = directions;
    return this;
  }

  public RouteOption addDirectionsItem(String directionsItem) {
    if (this.directions == null) {
      this.directions = new ArrayList<String>();
    }
    this.directions.add(directionsItem);
    return this;
  }

   /**
   * Get directions
   * @return directions
  **/
  @ApiModelProperty(value = "")
  public List<String> getDirections() {
    return directions;
  }

  public void setDirections(List<String> directions) {
    this.directions = directions;
  }

  public RouteOption lineIdentifier(Identifier lineIdentifier) {
    this.lineIdentifier = lineIdentifier;
    return this;
  }

   /**
   * The line identifier (e.g. District Line), from where you can obtain line status information e.g. the rainbow board status \&quot;good service\&quot;.
   * @return lineIdentifier
  **/
  @ApiModelProperty(value = "The line identifier (e.g. District Line), from where you can obtain line status information e.g. the rainbow board status \"good service\".")
  public Identifier getLineIdentifier() {
    return lineIdentifier;
  }

  public void setLineIdentifier(Identifier lineIdentifier) {
    this.lineIdentifier = lineIdentifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOption routeOption = (RouteOption) o;
    return Objects.equals(this.id, routeOption.id) &&
        Objects.equals(this.name, routeOption.name) &&
        Objects.equals(this.directions, routeOption.directions) &&
        Objects.equals(this.lineIdentifier, routeOption.lineIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, directions, lineIdentifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOption {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("    lineIdentifier: ").append(toIndentedString(lineIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

