/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * StatusSeverity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class StatusSeverity {
  @SerializedName("modeName")
  private String modeName = null;

  @SerializedName("severityLevel")
  private Integer severityLevel = null;

  @SerializedName("description")
  private String description = null;

  public StatusSeverity modeName(String modeName) {
    this.modeName = modeName;
    return this;
  }

   /**
   * Get modeName
   * @return modeName
  **/
  @ApiModelProperty(value = "")
  public String getModeName() {
    return modeName;
  }

  public void setModeName(String modeName) {
    this.modeName = modeName;
  }

  public StatusSeverity severityLevel(Integer severityLevel) {
    this.severityLevel = severityLevel;
    return this;
  }

   /**
   * Get severityLevel
   * @return severityLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getSeverityLevel() {
    return severityLevel;
  }

  public void setSeverityLevel(Integer severityLevel) {
    this.severityLevel = severityLevel;
  }

  public StatusSeverity description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusSeverity statusSeverity = (StatusSeverity) o;
    return Objects.equals(this.modeName, statusSeverity.modeName) &&
        Objects.equals(this.severityLevel, statusSeverity.severityLevel) &&
        Objects.equals(this.description, statusSeverity.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modeName, severityLevel, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusSeverity {\n");
    
    sb.append("    modeName: ").append(toIndentedString(modeName)).append("\n");
    sb.append("    severityLevel: ").append(toIndentedString(severityLevel)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

