/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * StopPointRouteSection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class StopPointRouteSection {
  @SerializedName("naptanId")
  private String naptanId = null;

  @SerializedName("lineId")
  private String lineId = null;

  @SerializedName("mode")
  private String mode = null;

  @SerializedName("validFrom")
  private OffsetDateTime validFrom = null;

  @SerializedName("validTo")
  private OffsetDateTime validTo = null;

  @SerializedName("direction")
  private String direction = null;

  @SerializedName("routeSectionName")
  private String routeSectionName = null;

  @SerializedName("lineString")
  private String lineString = null;

  @SerializedName("isActive")
  private Boolean isActive = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  @SerializedName("vehicleDestinationText")
  private String vehicleDestinationText = null;

  @SerializedName("destinationName")
  private String destinationName = null;

  public StopPointRouteSection naptanId(String naptanId) {
    this.naptanId = naptanId;
    return this;
  }

   /**
   * Get naptanId
   * @return naptanId
  **/
  @ApiModelProperty(value = "")
  public String getNaptanId() {
    return naptanId;
  }

  public void setNaptanId(String naptanId) {
    this.naptanId = naptanId;
  }

  public StopPointRouteSection lineId(String lineId) {
    this.lineId = lineId;
    return this;
  }

   /**
   * Get lineId
   * @return lineId
  **/
  @ApiModelProperty(value = "")
  public String getLineId() {
    return lineId;
  }

  public void setLineId(String lineId) {
    this.lineId = lineId;
  }

  public StopPointRouteSection mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(value = "")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public StopPointRouteSection validFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Get validFrom
   * @return validFrom
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
  }

  public StopPointRouteSection validTo(OffsetDateTime validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * Get validTo
   * @return validTo
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getValidTo() {
    return validTo;
  }

  public void setValidTo(OffsetDateTime validTo) {
    this.validTo = validTo;
  }

  public StopPointRouteSection direction(String direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @ApiModelProperty(value = "")
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public StopPointRouteSection routeSectionName(String routeSectionName) {
    this.routeSectionName = routeSectionName;
    return this;
  }

   /**
   * Get routeSectionName
   * @return routeSectionName
  **/
  @ApiModelProperty(value = "")
  public String getRouteSectionName() {
    return routeSectionName;
  }

  public void setRouteSectionName(String routeSectionName) {
    this.routeSectionName = routeSectionName;
  }

  public StopPointRouteSection lineString(String lineString) {
    this.lineString = lineString;
    return this;
  }

   /**
   * Get lineString
   * @return lineString
  **/
  @ApiModelProperty(value = "")
  public String getLineString() {
    return lineString;
  }

  public void setLineString(String lineString) {
    this.lineString = lineString;
  }

  public StopPointRouteSection isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public StopPointRouteSection serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Get serviceType
   * @return serviceType
  **/
  @ApiModelProperty(value = "")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }

  public StopPointRouteSection vehicleDestinationText(String vehicleDestinationText) {
    this.vehicleDestinationText = vehicleDestinationText;
    return this;
  }

   /**
   * Get vehicleDestinationText
   * @return vehicleDestinationText
  **/
  @ApiModelProperty(value = "")
  public String getVehicleDestinationText() {
    return vehicleDestinationText;
  }

  public void setVehicleDestinationText(String vehicleDestinationText) {
    this.vehicleDestinationText = vehicleDestinationText;
  }

  public StopPointRouteSection destinationName(String destinationName) {
    this.destinationName = destinationName;
    return this;
  }

   /**
   * Get destinationName
   * @return destinationName
  **/
  @ApiModelProperty(value = "")
  public String getDestinationName() {
    return destinationName;
  }

  public void setDestinationName(String destinationName) {
    this.destinationName = destinationName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopPointRouteSection stopPointRouteSection = (StopPointRouteSection) o;
    return Objects.equals(this.naptanId, stopPointRouteSection.naptanId) &&
        Objects.equals(this.lineId, stopPointRouteSection.lineId) &&
        Objects.equals(this.mode, stopPointRouteSection.mode) &&
        Objects.equals(this.validFrom, stopPointRouteSection.validFrom) &&
        Objects.equals(this.validTo, stopPointRouteSection.validTo) &&
        Objects.equals(this.direction, stopPointRouteSection.direction) &&
        Objects.equals(this.routeSectionName, stopPointRouteSection.routeSectionName) &&
        Objects.equals(this.lineString, stopPointRouteSection.lineString) &&
        Objects.equals(this.isActive, stopPointRouteSection.isActive) &&
        Objects.equals(this.serviceType, stopPointRouteSection.serviceType) &&
        Objects.equals(this.vehicleDestinationText, stopPointRouteSection.vehicleDestinationText) &&
        Objects.equals(this.destinationName, stopPointRouteSection.destinationName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(naptanId, lineId, mode, validFrom, validTo, direction, routeSectionName, lineString, isActive, serviceType, vehicleDestinationText, destinationName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopPointRouteSection {\n");
    
    sb.append("    naptanId: ").append(toIndentedString(naptanId)).append("\n");
    sb.append("    lineId: ").append(toIndentedString(lineId)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    routeSectionName: ").append(toIndentedString(routeSectionName)).append("\n");
    sb.append("    lineString: ").append(toIndentedString(lineString)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    vehicleDestinationText: ").append(toIndentedString(vehicleDestinationText)).append("\n");
    sb.append("    destinationName: ").append(toIndentedString(destinationName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

