/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * StopPointCategory
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class StopPointCategory {
  @SerializedName("category")
  private String category = null;

  @SerializedName("availableKeys")
  private List<String> availableKeys = null;

  public StopPointCategory category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public StopPointCategory availableKeys(List<String> availableKeys) {
    this.availableKeys = availableKeys;
    return this;
  }

  public StopPointCategory addAvailableKeysItem(String availableKeysItem) {
    if (this.availableKeys == null) {
      this.availableKeys = new ArrayList<String>();
    }
    this.availableKeys.add(availableKeysItem);
    return this;
  }

   /**
   * Get availableKeys
   * @return availableKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getAvailableKeys() {
    return availableKeys;
  }

  public void setAvailableKeys(List<String> availableKeys) {
    this.availableKeys = availableKeys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopPointCategory stopPointCategory = (StopPointCategory) o;
    return Objects.equals(this.category, stopPointCategory.category) &&
        Objects.equals(this.availableKeys, stopPointCategory.availableKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, availableKeys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopPointCategory {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    availableKeys: ").append(toIndentedString(availableKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

