/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * StopPoint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class StopPoint {
  @SerializedName("naptanId")
  private String naptanId = null;

  @SerializedName("platformName")
  private String platformName = null;

  @SerializedName("indicator")
  private String indicator = null;

  @SerializedName("stopLetter")
  private String stopLetter = null;

  @SerializedName("modes")
  private List<String> modes = null;

  @SerializedName("icsCode")
  private String icsCode = null;

  @SerializedName("smsCode")
  private String smsCode = null;

  @SerializedName("stopType")
  private String stopType = null;

  @SerializedName("stationNaptan")
  private String stationNaptan = null;

  @SerializedName("accessibilitySummary")
  private String accessibilitySummary = null;

  @SerializedName("hubNaptanCode")
  private String hubNaptanCode = null;

  @SerializedName("lines")
  private List<Identifier> lines = null;

  @SerializedName("lineGroup")
  private List<LineGroup> lineGroup = null;

  @SerializedName("lineModeGroups")
  private List<LineModeGroup> lineModeGroups = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("naptanMode")
  private String naptanMode = null;

  @SerializedName("status")
  private Boolean status = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("commonName")
  private String commonName = null;

  @SerializedName("distance")
  private Double distance = null;

  @SerializedName("placeType")
  private String placeType = null;

  @SerializedName("additionalProperties")
  private List<AdditionalProperties> additionalProperties = null;

  @SerializedName("children")
  private List<Place> children = null;

  @SerializedName("childrenUrls")
  private List<String> childrenUrls = null;

  @SerializedName("lat")
  private Double lat = null;

  @SerializedName("lon")
  private Double lon = null;

  public StopPoint naptanId(String naptanId) {
    this.naptanId = naptanId;
    return this;
  }

   /**
   * Get naptanId
   * @return naptanId
  **/
  @ApiModelProperty(value = "")
  public String getNaptanId() {
    return naptanId;
  }

  public void setNaptanId(String naptanId) {
    this.naptanId = naptanId;
  }

  public StopPoint platformName(String platformName) {
    this.platformName = platformName;
    return this;
  }

   /**
   * Get platformName
   * @return platformName
  **/
  @ApiModelProperty(value = "")
  public String getPlatformName() {
    return platformName;
  }

  public void setPlatformName(String platformName) {
    this.platformName = platformName;
  }

  public StopPoint indicator(String indicator) {
    this.indicator = indicator;
    return this;
  }

   /**
   * The indicator of the stop point e.g. \&quot;Stop K\&quot;
   * @return indicator
  **/
  @ApiModelProperty(value = "The indicator of the stop point e.g. \"Stop K\"")
  public String getIndicator() {
    return indicator;
  }

  public void setIndicator(String indicator) {
    this.indicator = indicator;
  }

  public StopPoint stopLetter(String stopLetter) {
    this.stopLetter = stopLetter;
    return this;
  }

   /**
   * The stop letter, if it could be cleansed from the Indicator e.g. \&quot;K\&quot;
   * @return stopLetter
  **/
  @ApiModelProperty(value = "The stop letter, if it could be cleansed from the Indicator e.g. \"K\"")
  public String getStopLetter() {
    return stopLetter;
  }

  public void setStopLetter(String stopLetter) {
    this.stopLetter = stopLetter;
  }

  public StopPoint modes(List<String> modes) {
    this.modes = modes;
    return this;
  }

  public StopPoint addModesItem(String modesItem) {
    if (this.modes == null) {
      this.modes = new ArrayList<String>();
    }
    this.modes.add(modesItem);
    return this;
  }

   /**
   * Get modes
   * @return modes
  **/
  @ApiModelProperty(value = "")
  public List<String> getModes() {
    return modes;
  }

  public void setModes(List<String> modes) {
    this.modes = modes;
  }

  public StopPoint icsCode(String icsCode) {
    this.icsCode = icsCode;
    return this;
  }

   /**
   * Get icsCode
   * @return icsCode
  **/
  @ApiModelProperty(value = "")
  public String getIcsCode() {
    return icsCode;
  }

  public void setIcsCode(String icsCode) {
    this.icsCode = icsCode;
  }

  public StopPoint smsCode(String smsCode) {
    this.smsCode = smsCode;
    return this;
  }

   /**
   * Get smsCode
   * @return smsCode
  **/
  @ApiModelProperty(value = "")
  public String getSmsCode() {
    return smsCode;
  }

  public void setSmsCode(String smsCode) {
    this.smsCode = smsCode;
  }

  public StopPoint stopType(String stopType) {
    this.stopType = stopType;
    return this;
  }

   /**
   * Get stopType
   * @return stopType
  **/
  @ApiModelProperty(value = "")
  public String getStopType() {
    return stopType;
  }

  public void setStopType(String stopType) {
    this.stopType = stopType;
  }

  public StopPoint stationNaptan(String stationNaptan) {
    this.stationNaptan = stationNaptan;
    return this;
  }

   /**
   * Get stationNaptan
   * @return stationNaptan
  **/
  @ApiModelProperty(value = "")
  public String getStationNaptan() {
    return stationNaptan;
  }

  public void setStationNaptan(String stationNaptan) {
    this.stationNaptan = stationNaptan;
  }

  public StopPoint accessibilitySummary(String accessibilitySummary) {
    this.accessibilitySummary = accessibilitySummary;
    return this;
  }

   /**
   * Get accessibilitySummary
   * @return accessibilitySummary
  **/
  @ApiModelProperty(value = "")
  public String getAccessibilitySummary() {
    return accessibilitySummary;
  }

  public void setAccessibilitySummary(String accessibilitySummary) {
    this.accessibilitySummary = accessibilitySummary;
  }

  public StopPoint hubNaptanCode(String hubNaptanCode) {
    this.hubNaptanCode = hubNaptanCode;
    return this;
  }

   /**
   * Get hubNaptanCode
   * @return hubNaptanCode
  **/
  @ApiModelProperty(value = "")
  public String getHubNaptanCode() {
    return hubNaptanCode;
  }

  public void setHubNaptanCode(String hubNaptanCode) {
    this.hubNaptanCode = hubNaptanCode;
  }

  public StopPoint lines(List<Identifier> lines) {
    this.lines = lines;
    return this;
  }

  public StopPoint addLinesItem(Identifier linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<Identifier>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @ApiModelProperty(value = "")
  public List<Identifier> getLines() {
    return lines;
  }

  public void setLines(List<Identifier> lines) {
    this.lines = lines;
  }

  public StopPoint lineGroup(List<LineGroup> lineGroup) {
    this.lineGroup = lineGroup;
    return this;
  }

  public StopPoint addLineGroupItem(LineGroup lineGroupItem) {
    if (this.lineGroup == null) {
      this.lineGroup = new ArrayList<LineGroup>();
    }
    this.lineGroup.add(lineGroupItem);
    return this;
  }

   /**
   * Get lineGroup
   * @return lineGroup
  **/
  @ApiModelProperty(value = "")
  public List<LineGroup> getLineGroup() {
    return lineGroup;
  }

  public void setLineGroup(List<LineGroup> lineGroup) {
    this.lineGroup = lineGroup;
  }

  public StopPoint lineModeGroups(List<LineModeGroup> lineModeGroups) {
    this.lineModeGroups = lineModeGroups;
    return this;
  }

  public StopPoint addLineModeGroupsItem(LineModeGroup lineModeGroupsItem) {
    if (this.lineModeGroups == null) {
      this.lineModeGroups = new ArrayList<LineModeGroup>();
    }
    this.lineModeGroups.add(lineModeGroupsItem);
    return this;
  }

   /**
   * Get lineModeGroups
   * @return lineModeGroups
  **/
  @ApiModelProperty(value = "")
  public List<LineModeGroup> getLineModeGroups() {
    return lineModeGroups;
  }

  public void setLineModeGroups(List<LineModeGroup> lineModeGroups) {
    this.lineModeGroups = lineModeGroups;
  }

  public StopPoint fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public StopPoint naptanMode(String naptanMode) {
    this.naptanMode = naptanMode;
    return this;
  }

   /**
   * Get naptanMode
   * @return naptanMode
  **/
  @ApiModelProperty(value = "")
  public String getNaptanMode() {
    return naptanMode;
  }

  public void setNaptanMode(String naptanMode) {
    this.naptanMode = naptanMode;
  }

  public StopPoint status(Boolean status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Boolean isStatus() {
    return status;
  }

  public void setStatus(Boolean status) {
    this.status = status;
  }

  public StopPoint id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier.
   * @return id
  **/
  @ApiModelProperty(value = "A unique identifier.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public StopPoint url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The unique location of this resource.
   * @return url
  **/
  @ApiModelProperty(value = "The unique location of this resource.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public StopPoint commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * A human readable name.
   * @return commonName
  **/
  @ApiModelProperty(value = "A human readable name.")
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public StopPoint distance(Double distance) {
    this.distance = distance;
    return this;
  }

   /**
   * The distance of the place from its search point, if this is the result              of a geographical search, otherwise zero.
   * @return distance
  **/
  @ApiModelProperty(value = "The distance of the place from its search point, if this is the result              of a geographical search, otherwise zero.")
  public Double getDistance() {
    return distance;
  }

  public void setDistance(Double distance) {
    this.distance = distance;
  }

  public StopPoint placeType(String placeType) {
    this.placeType = placeType;
    return this;
  }

   /**
   * The type of Place. See /Place/Meta/placeTypes for possible values.
   * @return placeType
  **/
  @ApiModelProperty(value = "The type of Place. See /Place/Meta/placeTypes for possible values.")
  public String getPlaceType() {
    return placeType;
  }

  public void setPlaceType(String placeType) {
    this.placeType = placeType;
  }

  public StopPoint additionalProperties(List<AdditionalProperties> additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

  public StopPoint addAdditionalPropertiesItem(AdditionalProperties additionalPropertiesItem) {
    if (this.additionalProperties == null) {
      this.additionalProperties = new ArrayList<AdditionalProperties>();
    }
    this.additionalProperties.add(additionalPropertiesItem);
    return this;
  }

   /**
   * A bag of additional key/value pairs with extra information about this place.
   * @return additionalProperties
  **/
  @ApiModelProperty(value = "A bag of additional key/value pairs with extra information about this place.")
  public List<AdditionalProperties> getAdditionalProperties() {
    return additionalProperties;
  }

  public void setAdditionalProperties(List<AdditionalProperties> additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  public StopPoint children(List<Place> children) {
    this.children = children;
    return this;
  }

  public StopPoint addChildrenItem(Place childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<Place>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<Place> getChildren() {
    return children;
  }

  public void setChildren(List<Place> children) {
    this.children = children;
  }

  public StopPoint childrenUrls(List<String> childrenUrls) {
    this.childrenUrls = childrenUrls;
    return this;
  }

  public StopPoint addChildrenUrlsItem(String childrenUrlsItem) {
    if (this.childrenUrls == null) {
      this.childrenUrls = new ArrayList<String>();
    }
    this.childrenUrls.add(childrenUrlsItem);
    return this;
  }

   /**
   * Get childrenUrls
   * @return childrenUrls
  **/
  @ApiModelProperty(value = "")
  public List<String> getChildrenUrls() {
    return childrenUrls;
  }

  public void setChildrenUrls(List<String> childrenUrls) {
    this.childrenUrls = childrenUrls;
  }

  public StopPoint lat(Double lat) {
    this.lat = lat;
    return this;
  }

   /**
   * WGS84 latitude of the location.
   * @return lat
  **/
  @ApiModelProperty(value = "WGS84 latitude of the location.")
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public StopPoint lon(Double lon) {
    this.lon = lon;
    return this;
  }

   /**
   * WGS84 longitude of the location.
   * @return lon
  **/
  @ApiModelProperty(value = "WGS84 longitude of the location.")
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopPoint stopPoint = (StopPoint) o;
    return Objects.equals(this.naptanId, stopPoint.naptanId) &&
        Objects.equals(this.platformName, stopPoint.platformName) &&
        Objects.equals(this.indicator, stopPoint.indicator) &&
        Objects.equals(this.stopLetter, stopPoint.stopLetter) &&
        Objects.equals(this.modes, stopPoint.modes) &&
        Objects.equals(this.icsCode, stopPoint.icsCode) &&
        Objects.equals(this.smsCode, stopPoint.smsCode) &&
        Objects.equals(this.stopType, stopPoint.stopType) &&
        Objects.equals(this.stationNaptan, stopPoint.stationNaptan) &&
        Objects.equals(this.accessibilitySummary, stopPoint.accessibilitySummary) &&
        Objects.equals(this.hubNaptanCode, stopPoint.hubNaptanCode) &&
        Objects.equals(this.lines, stopPoint.lines) &&
        Objects.equals(this.lineGroup, stopPoint.lineGroup) &&
        Objects.equals(this.lineModeGroups, stopPoint.lineModeGroups) &&
        Objects.equals(this.fullName, stopPoint.fullName) &&
        Objects.equals(this.naptanMode, stopPoint.naptanMode) &&
        Objects.equals(this.status, stopPoint.status) &&
        Objects.equals(this.id, stopPoint.id) &&
        Objects.equals(this.url, stopPoint.url) &&
        Objects.equals(this.commonName, stopPoint.commonName) &&
        Objects.equals(this.distance, stopPoint.distance) &&
        Objects.equals(this.placeType, stopPoint.placeType) &&
        Objects.equals(this.additionalProperties, stopPoint.additionalProperties) &&
        Objects.equals(this.children, stopPoint.children) &&
        Objects.equals(this.childrenUrls, stopPoint.childrenUrls) &&
        Objects.equals(this.lat, stopPoint.lat) &&
        Objects.equals(this.lon, stopPoint.lon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(naptanId, platformName, indicator, stopLetter, modes, icsCode, smsCode, stopType, stationNaptan, accessibilitySummary, hubNaptanCode, lines, lineGroup, lineModeGroups, fullName, naptanMode, status, id, url, commonName, distance, placeType, additionalProperties, children, childrenUrls, lat, lon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopPoint {\n");
    
    sb.append("    naptanId: ").append(toIndentedString(naptanId)).append("\n");
    sb.append("    platformName: ").append(toIndentedString(platformName)).append("\n");
    sb.append("    indicator: ").append(toIndentedString(indicator)).append("\n");
    sb.append("    stopLetter: ").append(toIndentedString(stopLetter)).append("\n");
    sb.append("    modes: ").append(toIndentedString(modes)).append("\n");
    sb.append("    icsCode: ").append(toIndentedString(icsCode)).append("\n");
    sb.append("    smsCode: ").append(toIndentedString(smsCode)).append("\n");
    sb.append("    stopType: ").append(toIndentedString(stopType)).append("\n");
    sb.append("    stationNaptan: ").append(toIndentedString(stationNaptan)).append("\n");
    sb.append("    accessibilitySummary: ").append(toIndentedString(accessibilitySummary)).append("\n");
    sb.append("    hubNaptanCode: ").append(toIndentedString(hubNaptanCode)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    lineGroup: ").append(toIndentedString(lineGroup)).append("\n");
    sb.append("    lineModeGroups: ").append(toIndentedString(lineModeGroups)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    naptanMode: ").append(toIndentedString(naptanMode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    placeType: ").append(toIndentedString(placeType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    childrenUrls: ").append(toIndentedString(childrenUrls)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

