/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * StreetSegment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class StreetSegment {
  @SerializedName("toid")
  private String toid = null;

  @SerializedName("lineString")
  private String lineString = null;

  @SerializedName("sourceSystemId")
  private Long sourceSystemId = null;

  @SerializedName("sourceSystemKey")
  private String sourceSystemKey = null;

  public StreetSegment toid(String toid) {
    this.toid = toid;
    return this;
  }

   /**
   * A 16 digit unique integer identifying a OS ITN (Ordnance Survey Integrated Transport Network) road link.
   * @return toid
  **/
  @ApiModelProperty(value = "A 16 digit unique integer identifying a OS ITN (Ordnance Survey Integrated Transport Network) road link.")
  public String getToid() {
    return toid;
  }

  public void setToid(String toid) {
    this.toid = toid;
  }

  public StreetSegment lineString(String lineString) {
    this.lineString = lineString;
    return this;
  }

   /**
   * geoJSON formatted LineString containing two latitude/longitude (WGS84) pairs that identify the start and end points of the street segment.
   * @return lineString
  **/
  @ApiModelProperty(value = "geoJSON formatted LineString containing two latitude/longitude (WGS84) pairs that identify the start and end points of the street segment.")
  public String getLineString() {
    return lineString;
  }

  public void setLineString(String lineString) {
    this.lineString = lineString;
  }

  public StreetSegment sourceSystemId(Long sourceSystemId) {
    this.sourceSystemId = sourceSystemId;
    return this;
  }

   /**
   * The ID from the source system of the disruption that this street belongs to.
   * @return sourceSystemId
  **/
  @ApiModelProperty(value = "The ID from the source system of the disruption that this street belongs to.")
  public Long getSourceSystemId() {
    return sourceSystemId;
  }

  public void setSourceSystemId(Long sourceSystemId) {
    this.sourceSystemId = sourceSystemId;
  }

  public StreetSegment sourceSystemKey(String sourceSystemKey) {
    this.sourceSystemKey = sourceSystemKey;
    return this;
  }

   /**
   * The key of the source system of the disruption that this street belongs to.
   * @return sourceSystemKey
  **/
  @ApiModelProperty(value = "The key of the source system of the disruption that this street belongs to.")
  public String getSourceSystemKey() {
    return sourceSystemKey;
  }

  public void setSourceSystemKey(String sourceSystemKey) {
    this.sourceSystemKey = sourceSystemKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreetSegment streetSegment = (StreetSegment) o;
    return Objects.equals(this.toid, streetSegment.toid) &&
        Objects.equals(this.lineString, streetSegment.lineString) &&
        Objects.equals(this.sourceSystemId, streetSegment.sourceSystemId) &&
        Objects.equals(this.sourceSystemKey, streetSegment.sourceSystemKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toid, lineString, sourceSystemId, sourceSystemKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreetSegment {\n");
    
    sb.append("    toid: ").append(toIndentedString(toid)).append("\n");
    sb.append("    lineString: ").append(toIndentedString(lineString)).append("\n");
    sb.append("    sourceSystemId: ").append(toIndentedString(sourceSystemId)).append("\n");
    sb.append("    sourceSystemKey: ").append(toIndentedString(sourceSystemKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

