/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * TimeAdjustments
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class TimeAdjustments {
  @SerializedName("earliest")
  private TimeAdjustment earliest = null;

  @SerializedName("earlier")
  private TimeAdjustment earlier = null;

  @SerializedName("later")
  private TimeAdjustment later = null;

  @SerializedName("latest")
  private TimeAdjustment latest = null;

  public TimeAdjustments earliest(TimeAdjustment earliest) {
    this.earliest = earliest;
    return this;
  }

   /**
   * Get earliest
   * @return earliest
  **/
  @ApiModelProperty(value = "")
  public TimeAdjustment getEarliest() {
    return earliest;
  }

  public void setEarliest(TimeAdjustment earliest) {
    this.earliest = earliest;
  }

  public TimeAdjustments earlier(TimeAdjustment earlier) {
    this.earlier = earlier;
    return this;
  }

   /**
   * Get earlier
   * @return earlier
  **/
  @ApiModelProperty(value = "")
  public TimeAdjustment getEarlier() {
    return earlier;
  }

  public void setEarlier(TimeAdjustment earlier) {
    this.earlier = earlier;
  }

  public TimeAdjustments later(TimeAdjustment later) {
    this.later = later;
    return this;
  }

   /**
   * Get later
   * @return later
  **/
  @ApiModelProperty(value = "")
  public TimeAdjustment getLater() {
    return later;
  }

  public void setLater(TimeAdjustment later) {
    this.later = later;
  }

  public TimeAdjustments latest(TimeAdjustment latest) {
    this.latest = latest;
    return this;
  }

   /**
   * Get latest
   * @return latest
  **/
  @ApiModelProperty(value = "")
  public TimeAdjustment getLatest() {
    return latest;
  }

  public void setLatest(TimeAdjustment latest) {
    this.latest = latest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeAdjustments timeAdjustments = (TimeAdjustments) o;
    return Objects.equals(this.earliest, timeAdjustments.earliest) &&
        Objects.equals(this.earlier, timeAdjustments.earlier) &&
        Objects.equals(this.later, timeAdjustments.later) &&
        Objects.equals(this.latest, timeAdjustments.latest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earliest, earlier, later, latest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeAdjustments {\n");
    
    sb.append("    earliest: ").append(toIndentedString(earliest)).append("\n");
    sb.append("    earlier: ").append(toIndentedString(earlier)).append("\n");
    sb.append("    later: ").append(toIndentedString(later)).append("\n");
    sb.append("    latest: ").append(toIndentedString(latest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

