/*
 * Transport for London Unified API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.tfl.api.client.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents a period for which a planned works is valid.
 */
@ApiModel(description = "Represents a period for which a planned works is valid.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T14:08:15.676-06:00")
public class ValidityPeriod {
  @SerializedName("fromDate")
  private OffsetDateTime fromDate = null;

  @SerializedName("toDate")
  private OffsetDateTime toDate = null;

  @SerializedName("isNow")
  private Boolean isNow = null;

  public ValidityPeriod fromDate(OffsetDateTime fromDate) {
    this.fromDate = fromDate;
    return this;
  }

   /**
   * Gets or sets the start date.
   * @return fromDate
  **/
  @ApiModelProperty(value = "Gets or sets the start date.")
  public OffsetDateTime getFromDate() {
    return fromDate;
  }

  public void setFromDate(OffsetDateTime fromDate) {
    this.fromDate = fromDate;
  }

  public ValidityPeriod toDate(OffsetDateTime toDate) {
    this.toDate = toDate;
    return this;
  }

   /**
   * Gets or sets the end date.
   * @return toDate
  **/
  @ApiModelProperty(value = "Gets or sets the end date.")
  public OffsetDateTime getToDate() {
    return toDate;
  }

  public void setToDate(OffsetDateTime toDate) {
    this.toDate = toDate;
  }

  public ValidityPeriod isNow(Boolean isNow) {
    this.isNow = isNow;
    return this;
  }

   /**
   * If true is a realtime status rather than planned or info
   * @return isNow
  **/
  @ApiModelProperty(value = "If true is a realtime status rather than planned or info")
  public Boolean isIsNow() {
    return isNow;
  }

  public void setIsNow(Boolean isNow) {
    this.isNow = isNow;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidityPeriod validityPeriod = (ValidityPeriod) o;
    return Objects.equals(this.fromDate, validityPeriod.fromDate) &&
        Objects.equals(this.toDate, validityPeriod.toDate) &&
        Objects.equals(this.isNow, validityPeriod.isNow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromDate, toDate, isNow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidityPeriod {\n");
    
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    isNow: ").append(toIndentedString(isNow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

